{% set version = "1.7.5" %}
{% set sha256 = "40d13ed2ba8347091e8ea27e7d068df436468254f6089ec243012abce1da44cd" %}

package:
  name: kmer-db
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/refresh-bio/kmer-db/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
 # patches:
 #   - fix_const_template.patch

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - kmer-db > /dev/null

about:
  home: https://github.com/refresh-bio/kmer-db
  summary: "Kmer-db is a fast and memory-efficient tool for estimating evolutionary distances."
  license: GPL-3
  license_family: GPL
  license_file: LICENSE
