{% set version = "1.7.7" %}
{% set sha256 = "2f2f2e423a3029c9b24835a80cdcfb5512c567b738bec305ce63bd7542be9667" %}


package:
  name: kmer-db
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/refresh-bio/kmer-db/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make 
  host:
    - zlib
  run:
    - zlib

about:
  home: https://github.com/refresh-bio/kmer-db
  summary: "Kmer-db is a fast and memory-efficient tool for estimating evolutionary distances."
  license: GPL-3
  license_family: GPL
  license_file: LICENSE

test:
  commands:
    - kmer-db > /dev/null
