{% set version = "1.0.2" %}

package:
  name: msisensor-pro
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/xjtu-omics/msisensor-pro/archive/{{ version }}.tar.gz 
  sha256: a28088d2d0ef32a2653fd404a17edd76540b28ab2bf301097ed33b9353b134a7

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }} 
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - zlib
    - ncurses
  run:
    - zlib
    - ncurses

about:
  home: https://github.com/xjtu-omics/msisensor-pro
  license: GPL-3.0
  license_file: LICENSE
  summary: Microsatellite Instability (MSI) detection using high-throughput sequencing data.

test:
  commands:
     - "msisensor-pro scan -h 2>&1 | grep Usage"
     - "msisensor-pro baseline -h 2>&1 | grep Usage"
     - "msisensor-pro pro -h 2>&1 | grep Usage"
     - "msisensor-pro msi -h 2>&1 | grep Usage"
