{% set version = "3.1" %}
{% set sha256_linux_x64 = "699c92795ffb8bd84f15b7f1469458e1a820b69328e2f8587215627003440c5f" %}
{% set sha256_linux_arm = "11afd7a6a468e5214281b5cf203c905a74b1971de7abf7a4cc49c43c26614ef9" %}
{% set sha256_mac_x64 = "7c29c7f4b83fac3b16f294c39d4cae82eeb22a8bf86dd8a6e25c8c7263e99d13" %}
{% set sha256_mac_m1 = "80944da6d5626376d9e618ff25875d8b7bbb7deb924ff45483e37cbf8628f02b" %}

package:
  name: agc
  version: {{ version }}

build:
  number: 0
  script: "mkdir -p ${PREFIX}/bin; cp agc ${PREFIX}/bin"

source:
  url: https://github.com/refresh-bio/agc/releases/download/v{{ version }}/agc-{{ version }}_arm_linux.tar.gz
  sha256: {{ sha256_linux_arm }}
  {% if target_platform == 'linux-64' %}
  url: https://github.com/refresh-bio/agc/releases/download/v{{ version }}/agc-{{ version }}_x64_linux.tar.gz
  sha256: {{ sha256_linux_x64 }}
  {% elif target_platform == 'linux-aarch64' %}
  url: https://github.com/refresh-bio/agc/releases/download/v{{ version }}/agc-{{ version }}_arm_linux.tar.gz
  sha256: {{ sha256_linux_arm }}
  {% elif target_platform == 'osx-64' %}
  url: https://github.com/refresh-bio/agc/releases/download/v{{ version }}/agc-{{ version }}_x64-mac.tar.gz
  sha256: {{ sha256_mac_x64 }}
  {% elif target_platform == 'osx-arm64' %}
  url: https://github.com/refresh-bio/agc/releases/download/v{{ version }}/agc-{{ version }}_m1_mac.tar.gz
  sha256: {{ sha256_mac_m1 }}
  {% endif %}
requirements:
  build:
  run: 
about:
  home: https://github.com/refresh-bio/agc
  summary: "Assembled Genomes Compressor (AGC) is a tool designed to compress collections of de-novo assembled genomes. It can be used for various types of datasets: short genomes (viruses) as well as long (humans)."
  license: MIT
test:
  commands:
    - agc
extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
  watch:
    enable: yes
