{% set version = "2.0" %}
{% set system = "linux"%}  # [linux]
{% set system = "mac"%}  # [osx]
{% set sha256 = "2d0dd57dd28a080913ef5066e3a48c4558d867ed44bd022c883e972a69ab2b4d" %}  # [linux]
{% set sha256 = "1ccbaa8e22cbe7f15cc5dd6f7177d1045c5ffae36cfcae52dd59b00f59bf4d9e" %}  # [osx]
package:
  name: agc
  version: {{ version }}
build:
  number: 0
  script: "mkdir -p ${PREFIX}/bin; cp agc ${PREFIX}/bin"
source:
  url: https://github.com/refresh-bio/agc/releases/download/v{{ version }}/agc-{{ version }}_x64-{{ system }}.tar.gz
  sha256: {{ sha256 }}
requirements:
  build:
  run:
about:
  home: https://github.com/refresh-bio/agc
  summary: "Assembled Genomes Compressor (AGC) is a tool designed to compress collections of de-novo assembled genomes. It can be used for various types of datasets: short genomes (viruses) as well as long (humans)."
  license: MIT
test:
  commands:
    - agc
extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
    watch:
      enable: yes
