{% set version = "1.1" %}
{% set system = "linux"%}  # [linux]
{% set system = "mac"%}  # [osx]
{% set sha256 = "b931022e38546ed0449d73f8380844457e97759d6f807da51c91a3554e2b2b74" %}  # [linux]
{% set sha256 = "032eb51bb80b886d4d75e2bbcc7b2fb3f9babdc81e098fc2aa8d8e04f897c94c" %}  # [osx]
package:
  name: agc
  version: {{ version }}
build:
  number: 0
  script: "mkdir -p ${PREFIX}/bin; cp agc ${PREFIX}/bin"
source:
  url: https://github.com/refresh-bio/agc/releases/download/v{{ version }}/agc-{{ version }}_x64-{{ system }}.tar.gz
  sha256: {{ sha256 }}
requirements:
  build:
  run:
about:
  home: https://github.com/refresh-bio/agc
  summary: "Assembled Genomes Compressor (AGC) is a tool designed to compress collections of de-novo assembled genomes. It can be used for various types of datasets: short genomes (viruses) as well as long (humans)."
  license: MIT
test:
  commands:
    - agc
extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
