{% set version = "3.1" %}

package:
  name: agc
  version: {{ version }}

build:
  number: 0
  script: "mkdir -p ${PREFIX}/bin; cp agc ${PREFIX}/bin"
  run_exports:
    - {{ pin_subpackage('agc', max_pin="x") }}
source:
  - url: https://github.com/refresh-bio/agc/releases/download/v{{ version }}/agc-{{ version }}_arm_linux.tar.gz # [aarch64]
    sha256: 11afd7a6a468e5214281b5cf203c905a74b1971de7abf7a4cc49c43c26614ef9                                           # [aarch64]
  - url: https://github.com/refresh-bio/agc/releases/download/v{{ version }}/agc-{{ version }}_x64_linux.tar.gz   # [linux64]
    sha256: 699c92795ffb8bd84f15b7f1469458e1a820b69328e2f8587215627003440c5f                                           # [linux64]
  - url: https://github.com/refresh-bio/agc/releases/download/v{{ version }}/agc-{{ version }}_x64-mac.tar.gz       # [osx and x86_64]
    sha256: 7c29c7f4b83fac3b16f294c39d4cae82eeb22a8bf86dd8a6e25c8c7263e99d13                                           # [osx and x86_64]
  - url: https://github.com/refresh-bio/agc/releases/download/v{{ version }}/agc-{{ version }}_m1_mac.tar.gz       # [osx and arm64]
    sha256: 80944da6d5626376d9e618ff25875d8b7bbb7deb924ff45483e37cbf8628f02b                                           # [osx and arm64]
requirements:
  build:
  run: 
about:
  home: https://github.com/refresh-bio/agc
  summary: "Assembled Genomes Compressor (AGC) is a tool designed to compress collections of de-novo assembled genomes. It can be used for various types of datasets: short genomes (viruses) as well as long (humans)."
  license: MIT
test:
  commands:
    - agc
extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
  watch:
    enable: yes
